#!/usr/bin/env bash
# display information about subdomains
# shellcheck disable=SC2086

printdomaininfo()
{
    printf "The subdomain $2 "
    dig "$2.$1" | awk '/^'"$2.$1"'\./ { print "is a " $4 " record and points to " $5 }'
}

if [ "$2" ]; then
    printdomaininfo $1 $2
else
    printdomaininfo $1 www
    printdomaininfo $1 lb-01
    printdomaininfo $1 web-01
    printdomaininfo $1 web-02
fi
