#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx restart
