#!/usr/bin/env bash
# redirect to 301 permanent
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo touch /etc/nginx/sites-available/redirect_me
sudo chmod 666 /etc/nginx/sites-available/redirect_me
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
