#!/usr/bin/env bash
# redirect to 301 permanent
sudo apt-get update
sudo apt-get -y install nginx
sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
