#!/usr/bin/env bash
# shellcheck disable=SC2154
# Install Nginx

sudo apt-get update
sudo apt-get -y install nginx
sed -i '/listen 80 default_server/a add_header X-Served-By \$HOSTNAME;' /etc/nginx/sites-available/default
service nginx restart
