#!/usr/bin/env bash
# Install Nginx

sudo apt-get update
sudo apt-get -y install nginx
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By '"$HOSTNAME"'; 
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}' > /etc/nginx/sites-available/default
service nginx restart
