#!/usr/bin/env bash
# Installing Load Balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo "frontend mohamedali.tech
bind *:80
mode http
default_backend web_servers
backend web_servers
balance roundrobin
server 109112-web-01 34.207.253.78:80 check
server 109112-web-02 3.84.239.44:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
