#!/usr/bin/env bash
# Bash script that configures a server to listen on port 80

rm /etc/nginx/sites-available/*
rm /etc/nginx/sites-enabled/*~
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
