#!/usr/bin/env bash
# Bash script that configures a server to listen on port 80

sudo sed -i 's/listen [0-9]\{2,5\}/listen 80/g' /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/
sudo service nginx restart
