#!/usr/bin/env bash
# Bash script that configures a server to listen on port 80

rm /etc/nginx/sites-enabled/default
sed -i 's/listen [0-9]\{2,5\}/listen 80/g' /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
