#!/usr/bin/env bash
sed -i 's/listen [0-9]\{2,5\}/listen 80/g' /etc/nginx/sites-available/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
