#!/usr/bin/env bash
# Config Nginx to run as nginx user not root
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
